FROM docker.m.daocloud.io/library/nginx:alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY app /usr/share/nginx/html/app

EXPOSE 80
